version: '3.8'

services:
  api:
    build: .
    container_name: newenshield-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newenshield_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=supersecreto
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15-alpine
    container_name: newenshield-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecreto
      - POSTGRES_DB=newenshield_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: newenshield-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
