name: API Continuous Integration & Delivery

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-publish:
    name: Build, Scan & Push
    runs-on: ubuntu-latest

    steps:
      # Descargar cÃ³digo
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      # Preparar Java 17
      - name: â˜• Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Compilar y Testear
      - name: ğŸ”¨ Build with Maven
        run: mvn clean package -DskipTests

      # AuditorÃ­a de seguridad con Trivy (CÃ³digo)
      - name: ğŸ›¡ï¸ Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Iniciar sesiÃ³n en Docker Hub
      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir y Subir la imagen Docker
      - name: ğŸš€ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/newenshield-api:latest
